# Generated by Django 4.1.7 on 2023-03-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='car',
            new_name='cart',
        ),
    ]
